export interface Recipe {
  id: number
  name: string
  image: string
  prepTimeMinutes: number
  cookTimeMinutes?: number
  servings: number
  difficulty: string
  cuisine: string
  rating?: number
  reviewCount?: number
  tags?: string[]
  ingredients: string[]
  instructions: string[]
  nutrition?: {
    calories: number
    protein: number
    carbs: number
    fat: number
  }
}

export const recipesData: Recipe[] = [
  {
    id: 1,
    name: "Nasi Gudeg Yogyakarta",
    image: "/images/recipes/gudeg-yogyakarta.jpg",
    prepTimeMinutes: 30,
    cookTimeMinutes: 180,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indonesian",
    rating: 4.8,
    reviewCount: 156,
    tags: ["Traditional", "Javanese", "Sweet"],
    ingredients: [
      "500g nangka muda, potong-potong",
      "200ml santan kental",
      "3 lembar daun salam",
      "2 batang serai",
      "3 cm lengkuas",
      "2 sdm gula merah",
      "1 sdt garam",
      "8 bawang merah",
      "4 bawang putih",
      "3 kemiri",
      "1 sdt ketumbar",
    ],
    instructions: [
      "Haluskan bumbu (bawang merah, bawang putih, kemiri, ketumbar) dan tumis hingga harum",
      "Masukkan nangka muda, aduk rata dengan bumbu",
      "Tambahkan santan, daun salam, serai, dan lengkuas",
      "Masak dengan api kecil selama 2-3 jam hingga berwarna coklat",
      "Tambahkan gula merah dan garam, aduk rata",
      "Masak hingga kuah mengental dan bumbu meresap sempurna",
      "Sajikan dengan nasi putih hangat dan pelengkap lainnya",
    ],
    nutrition: {
      calories: 320,
      protein: 8,
      carbs: 45,
      fat: 12,
    },
  },
  {
    id: 2,
    name: "Rendang Daging Sapi",
    image: "/images/recipes/rendang-sapi.jpg",
    prepTimeMinutes: 60,
    cookTimeMinutes: 240,
    servings: 6,
    difficulty: "Hard",
    cuisine: "Indonesian",
    rating: 4.9,
    reviewCount: 203,
    tags: ["Spicy", "Minang", "Beef"],
    ingredients: [
      "1kg daging sapi, potong kotak",
      "400ml santan kental",
      "3 lembar daun jeruk",
      "2 batang serai",
      "3 lembar daun kunyit",
      "2 sdm kelapa sangrai",
      "10 cabai merah",
      "5 bawang merah",
      "4 bawang putih",
      "3 cm jahe",
      "2 cm kunyit",
    ],
    instructions: [
      "Haluskan cabai merah, bawang merah, bawang putih, jahe, kunyit dengan kelapa sangrai",
      "Tumis bumbu halus hingga harum dan berminyak",
      "Masukkan daging sapi, aduk hingga berubah warna",
      "Tuang santan, tambahkan daun jeruk, serai, dan daun kunyit",
      "Masak dengan api sedang sambil terus diaduk",
      "Kecilkan api, masak 3-4 jam hingga kuah mengering",
      "Aduk sesekali agar tidak gosong",
      "Rendang siap disajikan dengan nasi putih",
    ],
    nutrition: {
      calories: 450,
      protein: 35,
      carbs: 8,
      fat: 28,
    },
  },
  {
    id: 3,
    name: "Soto Ayam Lamongan",
    image: "/images/recipes/soto-ayam.jpg",
    prepTimeMinutes: 30,
    cookTimeMinutes: 60,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Indonesian",
    rating: 4.6,
    reviewCount: 89,
    tags: ["Soup", "Chicken", "East Java"],
    ingredients: [
      "1 ekor ayam kampung",
      "2 liter air",
      "100g tauge",
      "2 butir telur rebus",
      "100g bihun",
      "2 batang daun bawang, iris",
      "2 batang seledri, iris",
      "6 bawang merah",
      "3 bawang putih",
      "2 cm jahe",
      "1 sdt merica",
    ],
    instructions: [
      "Rebus ayam dalam air hingga empuk, angkat dan suwir-suwir",
      "Saring kaldu ayam, sisihkan untuk kuah",
      "Haluskan bawang merah, bawang putih, jahe, dan merica",
      "Tumis bumbu halus hingga harum",
      "Masukkan bumbu tumis ke dalam kaldu ayam",
      "Didihkan dan bumbui dengan garam dan penyedap rasa",
      "Siapkan mangkuk, taruh bihun, tauge, dan ayam suwir",
      "Siram dengan kuah panas, taburi daun bawang dan seledri",
    ],
    nutrition: {
      calories: 280,
      protein: 25,
      carbs: 20,
      fat: 10,
    },
  },
  {
    id: 4,
    name: "Gado-gado Jakarta",
    image: "/images/recipes/gado-gado.jpg",
    prepTimeMinutes: 45,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Indonesian",
    rating: 4.5,
    reviewCount: 124,
    tags: ["Vegetarian", "Healthy", "Salad"],
    ingredients: [
      "100g kacang panjang, potong 3cm",
      "100g tauge",
      "2 buah kentang, rebus dan potong",
      "2 butir telur rebus",
      "100g tahu, goreng",
      "100g tempe, goreng",
      "Selada secukupnya",
      "Kerupuk untuk pelengkap",
      "200g kacang tanah sangrai",
      "3 cabai rawit",
      "2 cm kencur",
      "1 sdm gula merah",
      "1 sdt garam",
    ],
    instructions: [
      "Rebus kacang panjang dan tauge hingga matang, tiriskan",
      "Haluskan kacang tanah sangrai, cabai rawit, kencur, gula merah, dan garam",
      "Tambahkan air matang sedikit demi sedikit hingga kekentalan yang diinginkan",
      "Tata sayuran, tahu, tempe, dan telur di piring",
      "Siram dengan bumbu kacang",
      "Taburi kerupuk sebagai pelengkap",
      "Gado-gado siap disajikan",
    ],
    nutrition: {
      calories: 350,
      protein: 18,
      carbs: 25,
      fat: 22,
    },
  },
  {
    id: 5,
    name: "Bakso Malang",
    image: "/images/recipes/bakso-malang.jpg",
    prepTimeMinutes: 60,
    cookTimeMinutes: 45,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indonesian",
    rating: 4.7,
    reviewCount: 178,
    tags: ["Soup", "Beef", "East Java"],
    ingredients: [
      "500g daging sapi giling",
      "100g tepung tapioka",
      "2 butir telur",
      "3 siung bawang putih, haluskan",
      "1 sdt garam",
      "1/2 sdt merica",
      "2 liter kaldu sapi",
      "100g mie kuning",
      "100g tauge",
      "2 batang daun bawang",
      "Bawang goreng untuk taburan",
    ],
    instructions: [
      "Campur daging giling, tepung tapioka, telur, bawang putih, garam, dan merica",
      "Uleni hingga adonan kalis dan elastis",
      "Bentuk adonan menjadi bulatan-bulatan bakso",
      "Rebus bakso dalam air mendidih hingga mengapung",
      "Panaskan kaldu sapi, bumbui dengan garam dan merica",
      "Rebus mie kuning dan tauge sebentar",
      "Tata mie, tauge, dan bakso dalam mangkuk",
      "Siram dengan kaldu panas, taburi daun bawang dan bawang goreng",
    ],
    nutrition: {
      calories: 380,
      protein: 28,
      carbs: 30,
      fat: 15,
    },
  },
  {
    id: 6,
    name: "Pempek Palembang",
    image: "/images/recipes/pempek-palembang.jpg",
    prepTimeMinutes: 90,
    cookTimeMinutes: 30,
    servings: 3,
    difficulty: "Medium",
    cuisine: "Indonesian",
    rating: 4.6,
    reviewCount: 145,
    tags: ["Fish", "South Sumatra", "Fried"],
    ingredients: [
      "500g ikan tenggiri, haluskan",
      "250g tepung sagu",
      "2 sdt garam",
      "1 sdt gula",
      "300ml air",
      "Untuk kuah cuko:",
      "200g gula merah",
      "100ml air asam jawa",
      "5 cabai rawit",
      "3 siung bawang putih",
      "1 sdt garam",
    ],
    instructions: [
      "Campur ikan tenggiri halus dengan garam dan gula",
      "Tambahkan tepung sagu sedikit demi sedikit sambil diuleni",
      "Tuang air panas sedikit demi sedikit hingga adonan kalis",
      "Bentuk adonan sesuai selera (lenjer, kapal selam, dll)",
      "Rebus pempek dalam air mendidih hingga mengapung",
      "Untuk cuko: rebus gula merah dengan air asam jawa",
      "Haluskan cabai rawit, bawang putih, dan garam, campur dengan kuah",
      "Goreng pempek sebentar, sajikan dengan cuko",
    ],
    nutrition: {
      calories: 290,
      protein: 20,
      carbs: 35,
      fat: 8,
    },
  },
  {
    id: 7,
    name: "Rawon Surabaya",
    image: "/images/recipes/rawon-surabaya.jpg",
    prepTimeMinutes: 45,
    cookTimeMinutes: 120,
    servings: 5,
    difficulty: "Hard",
    cuisine: "Indonesian",
    rating: 4.8,
    reviewCount: 167,
    tags: ["Soup", "Beef", "East Java", "Black"],
    ingredients: [
      "1kg daging sapi, potong kotak",
      "3 buah kluwek, ambil isinya",
      "2 liter air",
      "3 lembar daun salam",
      "2 batang serai",
      "3 cm lengkuas",
      "8 bawang merah",
      "6 bawang putih",
      "5 cabai merah",
      "3 cm jahe",
      "2 cm kunyit",
      "1 sdt ketumbar",
    ],
    instructions: [
      "Rebus daging sapi hingga empuk, sisihkan kaldu",
      "Haluskan kluwek, bawang merah, bawang putih, cabai merah, jahe, kunyit, ketumbar",
      "Tumis bumbu halus hingga harum",
      "Masukkan daging sapi, aduk rata",
      "Tuang kaldu, tambahkan daun salam, serai, lengkuas",
      "Masak hingga daging empuk dan kuah berwarna hitam pekat",
      "Bumbui dengan garam dan penyedap rasa",
      "Sajikan dengan nasi putih, tauge, dan kerupuk",
    ],
    nutrition: {
      calories: 420,
      protein: 32,
      carbs: 12,
      fat: 25,
    },
  },
  {
    id: 8,
    name: "Kerak Telor Betawi",
    image: "/images/recipes/kerak-telor.png",
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 1,
    difficulty: "Medium",
    cuisine: "Indonesian",
    rating: 4.4,
    reviewCount: 92,
    tags: ["Traditional", "Betawi", "Street Food"],
    ingredients: [
      "3 sdm beras ketan putih",
      "1 butir telur ayam/bebek",
      "2 sdm ebi, sangrai dan tumbuk",
      "2 sdm kelapa sangrai",
      "1 sdm bawang goreng",
      "1 cabai rawit, iris",
      "1/2 sdt garam",
      "Minyak untuk menggoreng",
    ],
    instructions: [
      "Rendam beras ketan selama 2 jam, tiriskan",
      "Panaskan wajan anti lengket dengan sedikit minyak",
      "Masukkan beras ketan, ratakan",
      "Pecahkan telur di atas ketan, ratakan",
      "Taburi ebi, kelapa sangrai, bawang goreng",
      "Masak hingga bagian bawah kecoklatan dan renyah",
      "Balik dengan spatula, masak sebentar",
      "Angkat, taburi cabai rawit dan garam",
    ],
    nutrition: {
      calories: 250,
      protein: 12,
      carbs: 28,
      fat: 10,
    },
  },
  {
    id: 9,
    name: "Coto Makassar",
    image: "/images/recipes/coto-makassar.jpg",
    prepTimeMinutes: 60,
    cookTimeMinutes: 180,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indonesian",
    rating: 4.7,
    reviewCount: 134,
    tags: ["Soup", "Beef", "South Sulawesi"],
    ingredients: [
      "500g daging sapi",
      "200g jeroan sapi (hati, paru, usus)",
      "2 liter air",
      "100g kacang tanah, sangrai",
      "3 cm jahe",
      "4 siung bawang putih",
      "1 sdt ketumbar",
      "1 sdt jinten",
      "3 lembar daun jeruk",
      "2 batang serai",
      "Ketupat untuk pelengkap",
    ],
    instructions: [
      "Rebus daging dan jeroan hingga empuk, potong-potong",
      "Saring kaldu, sisihkan",
      "Sangrai kacang tanah, haluskan bersama jahe, bawang putih, ketumbar, jinten",
      "Tumis bumbu halus hingga harum",
      "Masukkan bumbu ke dalam kaldu",
      "Tambahkan daun jeruk dan serai",
      "Masukkan daging dan jeroan, masak hingga bumbu meresap",
      "Sajikan dengan ketupat dan sambal",
    ],
    nutrition: {
      calories: 390,
      protein: 30,
      carbs: 15,
      fat: 22,
    },
  },
  {
    id: 10,
    name: "Ayam Betutu Bali",
    image: "/images/recipes/ayam-betutu.jpg",
    prepTimeMinutes: 120,
    cookTimeMinutes: 240,
    servings: 6,
    difficulty: "Hard",
    cuisine: "Indonesian",
    rating: 4.9,
    reviewCount: 189,
    tags: ["Chicken", "Balinese", "Spicy"],
    ingredients: [
      "1 ekor ayam utuh",
      "10 cabai merah",
      "15 bawang merah",
      "8 bawang putih",
      "5 cm jahe",
      "3 cm kunyit",
      "3 cm kencur",
      "5 kemiri",
      "2 sdt ketumbar",
      "3 lembar daun salam",
      "2 batang serai",
      "Daun pisang untuk membungkus",
    ],
    instructions: [
      "Bersihkan ayam, lumuri dengan garam dan jeruk nipis",
      "Haluskan semua bumbu kecuali daun salam dan serai",
      "Lumuri ayam dengan bumbu halus hingga merata",
      "Masukkan daun salam dan serai ke dalam perut ayam",
      "Bungkus ayam dengan daun pisang rapat-rapat",
      "Panggang dalam oven 200°C selama 4 jam",
      "Atau kukus selama 3 jam lalu bakar sebentar",
      "Sajikan dengan nasi putih dan lalapan",
    ],
    nutrition: {
      calories: 380,
      protein: 35,
      carbs: 5,
      fat: 24,
    },
  },
  {
    id: 11,
    name: "Mie Aceh",
    image: "/images/recipes/mie-aceh.jpg",
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    servings: 2,
    difficulty: "Medium",
    cuisine: "Indonesian",
    rating: 4.6,
    reviewCount: 156,
    tags: ["Noodles", "Spicy", "Aceh"],
    ingredients: [
      "200g mie kuning",
      "200g daging sapi, iris tipis",
      "100g udang",
      "100g tauge",
      "2 butir telur",
      "3 sdm minyak goreng",
      "10 cabai merah",
      "6 bawang merah",
      "4 bawang putih",
      "2 cm jahe",
      "1 sdt jinten",
      "Daun bawang dan seledri",
    ],
    instructions: [
      "Rebus mie kuning hingga matang, tiriskan",
      "Haluskan cabai merah, bawang merah, bawang putih, jahe, jinten",
      "Tumis bumbu halus hingga harum",
      "Masukkan daging sapi, masak hingga berubah warna",
      "Tambahkan udang, masak hingga matang",
      "Masukkan telur, orak-arik",
      "Tambahkan mie dan tauge, aduk rata",
      "Taburi daun bawang dan seledri, sajikan panas",
    ],
    nutrition: {
      calories: 420,
      protein: 28,
      carbs: 35,
      fat: 18,
    },
  },
  {
    id: 12,
    name: "Papeda Papua",
    image: "/images/recipes/papeda-papua.jpg",
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 3,
    difficulty: "Easy",
    cuisine: "Indonesian",
    rating: 4.3,
    reviewCount: 67,
    tags: ["Traditional", "Papua", "Healthy"],
    ingredients: [
      "200g tepung sagu",
      "1 liter air",
      "1 sdt garam",
      "Untuk kuah ikan:",
      "500g ikan kakap",
      "3 ruas kunyit",
      "5 cabai rawit",
      "3 siung bawang merah",
      "2 lembar daun jeruk",
      "1 batang serai",
    ],
    instructions: [
      "Didihkan air dengan garam",
      "Masukkan tepung sagu sedikit demi sedikit sambil diaduk",
      "Aduk terus hingga mengental seperti lem",
      "Untuk kuah: rebus ikan dengan kunyit hingga matang",
      "Haluskan cabai rawit dengan bawang merah",
      "Tumis bumbu halus, masukkan ke kuah ikan",
      "Tambahkan daun jeruk dan serai",
      "Sajikan papeda dengan kuah ikan panas",
    ],
    nutrition: {
      calories: 180,
      protein: 15,
      carbs: 25,
      fat: 3,
    },
  },
  {
    id: 13,
    name: "Nasi Liwet Solo",
    image: "/images/recipes/nasi-liwet.jpg",
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Indonesian",
    rating: 4.5,
    reviewCount: 112,
    tags: ["Rice", "Javanese", "Coconut"],
    ingredients: [
      "400g beras",
      "400ml santan",
      "300ml air",
      "2 lembar daun salam",
      "1 batang serai",
      "1 sdt garam",
      "Pelengkap:",
      "Ayam goreng",
      "Telur pindang",
      "Tahu bacem",
      "Sambal goreng krecek",
    ],
    instructions: [
      "Cuci beras hingga bersih",
      "Campur santan, air, daun salam, serai, dan garam",
      "Masak beras dengan campuran santan hingga air menyusut",
      "Pindahkan ke dandang, kukus hingga matang",
      "Siapkan pelengkap: ayam goreng, telur pindang, tahu bacem",
      "Buat sambal goreng krecek",
      "Sajikan nasi liwet dengan semua pelengkap",
      "Hidangkan di atas daun pisang untuk aroma khas",
    ],
    nutrition: {
      calories: 350,
      protein: 12,
      carbs: 55,
      fat: 10,
    },
  },
  {
    id: 14,
    name: "Pecel Lele",
    image: "/images/recipes/pecel-lele.jpg",
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Indonesian",
    rating: 4.4,
    reviewCount: 98,
    tags: ["Fish", "Fried", "Javanese"],
    ingredients: [
      "4 ekor ikan lele",
      "2 sdt garam",
      "1 sdt kunyit bubuk",
      "Minyak untuk menggoreng",
      "Untuk sambal:",
      "10 cabai rawit",
      "3 cabai merah",
      "5 bawang merah",
      "3 siung bawang putih",
      "1 cm kencur",
      "1 sdt terasi",
      "Garam dan gula secukupnya",
    ],
    instructions: [
      "Bersihkan ikan lele, buat sayatan di bagian samping",
      "Lumuri dengan garam dan kunyit, diamkan 30 menit",
      "Goreng ikan lele hingga kering dan kecoklatan",
      "Untuk sambal: goreng semua bahan sambal kecuali garam dan gula",
      "Haluskan bahan sambal yang sudah digoreng",
      "Tambahkan garam dan gula, aduk rata",
      "Sajikan ikan lele dengan sambal dan lalapan",
      "Lengkapi dengan nasi putih hangat",
    ],
    nutrition: {
      calories: 320,
      protein: 25,
      carbs: 8,
      fat: 20,
    },
  },
  {
    id: 15,
    name: "Sate Padang",
    image: "/images/recipes/sate-padang.jpg",
    prepTimeMinutes: 60,
    cookTimeMinutes: 90,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Indonesian",
    rating: 4.7,
    reviewCount: 143,
    tags: ["Beef", "Grilled", "Minang"],
    ingredients: [
      "500g daging sapi, potong kotak",
      "Tusuk sate secukupnya",
      "Untuk bumbu:",
      "8 bawang merah",
      "4 bawang putih",
      "5 cabai merah",
      "2 cm jahe",
      "2 cm kunyit",
      "1 sdt ketumbar",
      "Untuk kuah:",
      "200ml santan",
      "2 sdm tepung beras",
      "Kaldu sapi secukupnya",
    ],
    instructions: [
      "Rebus daging sapi hingga empuk, potong kotak kecil",
      "Haluskan semua bumbu, tumis hingga harum",
      "Lumuri daging dengan bumbu, diamkan 1 jam",
      "Tusuk daging dengan tusuk sate",
      "Bakar sate sambil diolesi sisa bumbu",
      "Untuk kuah: campur santan, tepung beras, dan kaldu",
      "Masak kuah hingga mengental, bumbui dengan garam",
      "Sajikan sate dengan kuah kental dan ketupat",
    ],
    nutrition: {
      calories: 380,
      protein: 30,
      carbs: 12,
      fat: 22,
    },
  },
]

// Helper functions
export const getAllRecipes = (): Recipe[] => {
  return recipesData
}

export const getRecipeById = (id: number): Recipe | undefined => {
  return recipesData.find((recipe) => recipe.id === id)
}

export const getFeaturedRecipes = (limit = 6): Recipe[] => {
  return recipesData.slice(0, limit)
}

export const searchRecipes = (query: string): Recipe[] => {
  if (!query.trim()) return recipesData

  const lowercaseQuery = query.toLowerCase()
  return recipesData.filter(
    (recipe) =>
      recipe.name.toLowerCase().includes(lowercaseQuery) ||
      recipe.cuisine.toLowerCase().includes(lowercaseQuery) ||
      recipe.difficulty.toLowerCase().includes(lowercaseQuery) ||
      recipe.tags?.some((tag) => tag.toLowerCase().includes(lowercaseQuery)),
  )
}
